ENV["MPLBACKEND"] = get(ENV, "MPLBACKEND", "Agg")
import PyPlot as plt
import LaTeXStrings: @L_str
import LinearAlgebra: norm
include(joinpath(pnl.examples_path, "plotformat.jl"))
plt.ioff()

# ----------------- COMPARISON TO EXPERIMENTAL DATA ----------------------------
#=
    NOTE: Here we take a slice of the body and plot the velocity distribution
    along the slice.
=#

# Get a slice of the body
position        = 0.0        # Position of slice (slice along origin)
direction       = [0, 1, 0]  # Direction of slice (slice along the xz-plane)
row             = false      # If true, it slices along azimuth; centerline if false

gdims = split_dim == 1 ? (2 * (size(points, 1) - 1), NDIVS_theta) :
                         (size(points, 1) - 1, 2 * NDIVS_theta)
@assert prod(gdims) == body.ncells

lin = LinearIndices(gdims)

# Pick the azimuthal column closest to the xz-plane and on the upper half-body.
scores = fill(Inf, gdims[2])
for j in 1:gdims[2]
    column = [lin[i, j] for i in 1:gdims[1]]
    mean_y = sum(abs, view(body.controlpoints, 2, column)) / length(column)
    mean_z = sum(view(body.controlpoints, 3, column)) / length(column)
    if mean_z > 0
        scores[j] = mean_y
    end
end

jslice = argmin(scores)
slice_indices = [lin[i, jslice] for i in 1:gdims[1]]

# Average the triangle pairs generated by the structured split.
slicepoints = hcat([
    0.5 * (body.controlpoints[:, slice_indices[2i - 1]] + body.controlpoints[:, slice_indices[2i]])
    for i in 1:(length(slice_indices) ÷ 2)
]...)
sliceCps = [
    0.5 * (body.Cp[slice_indices[2i - 1]] + body.Cp[slice_indices[2i]])
    for i in 1:(length(slice_indices) ÷ 2)
]
sliceUs = [
    0.5 * (body.velocity[:, slice_indices[2i - 1]] + body.velocity[:, slice_indices[2i]])
    for i in 1:(length(slice_indices) ÷ 2)
]

perm = sortperm(view(slicepoints, 1, :))
slicepoints = slicepoints[:, perm]
sliceCps = sliceCps[perm]
sliceUs = sliceUs[perm]

# Plot experimental surface velocity distribution (figure 4.6 in Lewis 1991)
fig = plt.figure(figsize=[7, 5*0.8]*2/3)
ax = fig.gca()

filename = joinpath(pnl.examples_path, "data",
                                "centerbody-lewis-fig4p6.csv")
VoVinf_lewis = CSV.read(filename, DataFrame)

ax.plot(VoVinf_lewis[:, 1], VoVinf_lewis[:, 2], "ok",
                            markersize=5, label="Experimental")

# Plot surface velocity distribution of FLOWPanel
ax.plot(slicepoints[1, :], norm.(sliceUs)/magVinf, "-", color="cyan",
                            linewidth=2.0, alpha=0.9, label="FLOWPanel")

# Plot contour of centerbody
ax2 = ax.twinx()
xs = vcat(slicepoints[1, :], reverse(slicepoints[1, :]), slicepoints[1, 1])
ys = vcat(slicepoints[3, :], -reverse(slicepoints[3, :]), slicepoints[3, 1])
ax2.plot(xs, ys, "-k", alpha=0.25)

# Beautify the plot
xlims = [-0.1, 1.5]
ylims = [-0.5, 1.5]
ax.set_xlim(xlims)
ax.set_xticks(0:0.5:1.5)
ax.set_ylim(ylims)
ax.set_yticks(0:0.5:1.5)

ax2.set_aspect(1.0)
ax2.set_ylim([-0.62, 1])
ax2.set_yticks([])
ax2.plot(xlims, zeros(2), ":k", alpha=0.25, linewidth=1)

ax.set_xlabel(L"$x$-position (m)")
ax.set_ylabel(L"Velocity $u/u_\infty$")
ax.legend(loc="best", frameon=false, fontsize=8)

for a in [ax, ax2]
    a.spines["right"].set_visible(false)
    a.spines["top"].set_visible(false)
end

fig.tight_layout()
