## BRAINSTORM item 003: CCBlade/BEM cross-check of the DJI 9443 rotor hover CT.
##
## The panel method gives a converged hover CT ~ 0.0506 while experiment/VPM is
## ~0.072. This script runs a blade-element-momentum (CCBlade) prediction using
## the *same* blade geometry (CST airfoil sections), operating point, density,
## and RPM, with section polars generated by XFOIL at the local Reynolds/Mach.
## The goal is to route the investigation: if BEM reaches ~0.072 while the panel
## stays low, the issue is wake/induced-velocity modeling; if BEM is also low,
## revisit section data / operating-condition interpretation.
##
## Operating point matches examples/rotor_hover_convergence.jl (RPM=5400).
## CT is reported with the FLOWPanel RotorNormalization convention CT=T/(rho n^2 D^4),
## which is exactly CCBlade's nondim(..., "propeller") convention.

using CCBlade
import Xfoil
import CSV
using DataFrames: DataFrame
import PythonPlot as plt
import FLOWMath
using Printf: @printf, @sprintf
using LinearAlgebra: norm

# ------------------------------------------------------------------ inputs ----
const CST_CSV   = get(ENV, "CST_CSV", joinpath(@__DIR__, "..", "dji9443_brainstorm_item003.csv"))
const SAVE_PATH = joinpath(@__DIR__, "..", "data", "rotor_hover_ccblade")

# Geometry / operating point (see rotor_hover_convergence.jl)
const RPM   = parse(Float64, get(ENV, "RPM", "5400"))
const R     = 0.119                 # tip radius [m]
const B     = 2                     # number of blades
const RHUB  = 0.1 * R               # hub radius [m] (shedding_r_over_R = 0.1)
const RHO   = 1.179                 # density [kg/m^3] (NASA paper)
const MU    = 1.69e-5               # dynamic viscosity [kg/m/s] (wake_nu_default*rho)
const ASOUND = 340.0                # speed of sound [m/s]
const OMEGA = 2pi * RPM / 60        # [rad/s]
const NREV  = RPM / 60              # rev/s
const D     = 2R

# Twist sign: CCBlade `theta` is pitch up (toward thrust) positive. The scan CSV
# stores `twist_rad` with the opposite sign, so negate. If integrated thrust
# comes out negative, flip THETA_SIGN.
const THETA_SIGN = parse(Float64, get(ENV, "THETA_SIGN", "-1.0"))

# Whether to include Mach (Prandtl-Glauert) in the XFOIL solves.
const USE_MACH = parse(Bool, get(ENV, "USE_MACH", "true"))

# XFOIL transition parameter (e^N critical amplification factor). Higher ncrit =
# later transition / quieter inflow (9 = clean-tunnel default, 14 = very quiet).
# Polars are rebuilt per ncrit so the BEM CT can be compared across values.
const NCRIT_LIST = let s = get(ENV, "NCRIT_LIST", "")
    isempty(s) ? [1, 4, 9, 14] : parse.(Int, split(s, ','))
end

# Climb velocities [m/s] to evaluate. Hover is approximated with a tiny nonzero
# Vc (pure Vx=0 is degenerate in BEM). Add nonzero entries to build a J sweep
# (J = Vc / (n D)) once experimental advance-ratio data is identified.
const VC_LIST = let s = get(ENV, "VC_LIST", "")
    isempty(s) ? [0.0001, 1.0, 2.0, 4.0] : parse.(Float64, split(s, ','))
end

# Reference values for plotting context.
const CT_PANEL = 0.0506
const CT_EXPERIMENT = 0.072

# ------------------------------------------------- CST reconstruction ---------
# Ported from examples/rotor_hover_scan/process_scan.jl (lines 508-534).
const CST_NCOEFFS = 8
const CST_NPTS = 161

bernstein(r, n, x) = binomial(n, r) .* x .^ r .* (1 .- x) .^ (n .- r)

function half_cst(coefficients, x, dz, leading_edge_weight; N1=0.5, N2=1.0)
    nb = length(coefficients) - 1
    C = @. x^N1 * (1.0 - x)^N2
    S = zero.(x)
    for (i, coefficient) in enumerate(coefficients)
        S .+= coefficient .* bernstein(i - 1, nb, x)
    end
    y = @. C * S + x * dz
    y .+= leading_edge_weight .* x .* (1.0 .- x) .^ (length(coefficients) + 0.5)
    return y
end

"Return chord-normalized Selig coordinates (TE -> upper -> LE -> lower -> TE)."
function cst_coordinates(p; N::Int=CST_NPTS)
    np = Int((length(p) - 2) / 2)
    pu = p[1:np]
    pl = p[(np + 1):(2 * np)]
    leading_edge_weight = p[end - 1]
    dz = p[end]
    θ = range(0.0, π; length=N)
    xu = @. 0.5 * (1.0 - cos(θ))
    xl = copy(xu)
    yu = half_cst(pu, xu, dz / 2.0, leading_edge_weight)
    yl = half_cst(pl, xl, -dz / 2.0, leading_edge_weight)
    return vcat(reverse(xu), xl[2:end]), vcat(reverse(yu), yl[2:end])
end

# --------------------------------------------------- XFOIL polar helper -------
"""
Run a robust XFOIL alpha sweep on (x, y) at the given Reynolds/Mach. Sweeps
outward from alpha=0 in both directions reusing the previous boundary-layer
solution; reinitializes on a failed point. Returns sorted (alpha_deg, cl, cd)
for converged points only.
"""
function xfoil_polar(x, y, re, mach; alpha_max=20.0, alpha_min=-12.0, dalpha=0.5,
                     iter=100, ncrit=9)
    Xfoil.set_coordinates(x, y)
    Xfoil.pane()

    results = Dict{Float64,Tuple{Float64,Float64}}()

    sweep_branch = function (alphas)
        first = true
        for a in alphas
            cl, cd, _, _, conv = Xfoil.solve_alpha(a, re; mach=mach, iter=iter,
                                                   ncrit=ncrit, reinit=first)
            first = false
            if conv && isfinite(cl) && isfinite(cd)
                results[a] = (cl, cd)
            else
                # reinitialize for the next angle so one bad point doesn't poison the branch
                first = true
            end
        end
    end

    sweep_branch(0.0:dalpha:alpha_max)
    sweep_branch(0.0:-dalpha:alpha_min)

    αs = sort!(collect(keys(results)))
    cls = [results[a][1] for a in αs]
    cds = [results[a][2] for a in αs]
    return αs, cls, cds
end

# ------------------------------------------------------------------ main ------
mkpath(SAVE_PATH)

println("Reading CST sections from $(CST_CSV)")
csv = CSV.read(CST_CSV, DataFrame)
nrows = size(csv, 1)
println("  $(nrows) sections in file")

# Build per-section geometry, dropping sections inside the hub or beyond the tip.
sec_r = Float64[]            # [m]
sec_chord = Float64[]        # [m]
sec_theta = Float64[]        # [rad]
sec_x = Vector{Vector{Float64}}()
sec_y = Vector{Vector{Float64}}()

for row in eachrow(csv)
    r_m = row.r / 1000          # mm -> m
    c_m = row.chord / 1000      # mm -> m
    if r_m <= RHUB || r_m >= R
        @printf("  skip section r=%.2f mm (outside [%.1f, %.1f] mm)\n",
                row.r, 1000RHUB, 1000R)
        continue
    end
    p = vcat([row[Symbol("wu$i")] for i in 1:CST_NCOEFFS],
             [row[Symbol("wl$i")] for i in 1:CST_NCOEFFS],
             row.leading_edge_weight, row.dz)
    x, y = cst_coordinates(p)
    push!(sec_r, r_m); push!(sec_chord, c_m)
    push!(sec_theta, THETA_SIGN * row.twist_rad)
    push!(sec_x, x); push!(sec_y, y)
end
nsec = length(sec_r)
println("  using $(nsec) sections, r/R in [$(round(minimum(sec_r)/R, digits=3)), $(round(maximum(sec_r)/R, digits=3))]")

# chord at 75% R for Viterna aspect-ratio estimate
cr75 = FLOWMath.linear(sec_r, sec_chord, 0.75R) / R

# Per-section hover Reynolds/Mach (independent of ncrit; W ~ tangential speed).
sec_Re = zeros(nsec)
sec_Mach = zeros(nsec)
for i in 1:nsec
    W = OMEGA * sec_r[i]                       # hover inflow ~ tangential speed
    sec_Re[i] = RHO * W * sec_chord[i] / MU
    sec_Mach[i] = USE_MACH ? clamp(W / ASOUND, 0.0, 0.6) : 0.0
end

rotor = Rotor(RHUB, R, B; precone=0.0, turbine=false)

radial_rows = DataFrame()
ct_rows = DataFrame(ncrit=Int[], Vc=Float64[], J=Float64[], T=Float64[], Q=Float64[],
                    CT=Float64[], CQ=Float64[], eff=Float64[])

# Converged XFOIL lift-polar data per (ncrit, section), kept for plotting/CSV.
# polar_data[ncrit][i] = (alpha_deg, cl, cd) for the converged sweep points.
polar_data = Dict{Int,Vector{NamedTuple{(:alpha_deg, :cl, :cd),Tuple{Vector{Float64},Vector{Float64},Vector{Float64}}}}}()

# Build polars and run the BEM op-point sweep once per ncrit. Polars are built
# once per (section, ncrit) at hover Re and reused across the J sweep.
for ncrit in NCRIT_LIST
    println("\n=== ncrit = $(ncrit) ===")
    println("Generating XFOIL polars (Re from hover inflow W = Omega*r)...")
    airfoils = Vector{Any}(undef, nsec)
    polar_data[ncrit] = Vector{NamedTuple{(:alpha_deg, :cl, :cd),Tuple{Vector{Float64},Vector{Float64},Vector{Float64}}}}(undef, nsec)
    for i in 1:nsec
        re = sec_Re[i]; mach = sec_Mach[i]
        αs, cls, cds = xfoil_polar(sec_x[i], sec_y[i], re, mach; ncrit=ncrit)
        @printf("  section %2d  r/R=%.3f  Re=%6.0f  M=%.2f  -> %d converged points\n",
                i, sec_r[i]/R, re, mach, length(αs))
        if length(αs) < 4
            error("Section $i (r/R=$(round(sec_r[i]/R,digits=3))) produced too few converged " *
                  "XFOIL points ($(length(αs))) at ncrit=$(ncrit). Try lowering alpha range or USE_MACH=false.")
        end
        polar_data[ncrit][i] = (alpha_deg=αs, cl=cls, cd=cds)
        # extrapolate to +/-180 deg (Viterna expects radians) and build the airfoil
        a_ext, cl_ext, cd_ext = viterna(deg2rad.(αs), cls, cds, cr75)
        airfoils[i] = AlphaAF(a_ext, cl_ext, cd_ext,
                              @sprintf("dji9443 r/R=%.3f Re=%.0f ncrit=%d", sec_r[i]/R, re, ncrit),
                              re, mach)
    end

    sections = Section.(sec_r, sec_chord, sec_theta, airfoils)

    println("Solving BEM over $(length(VC_LIST)) operating point(s)...")
    for Vc in VC_LIST
        J = Vc / (NREV * D)
        ops = simple_op.(Vc, OMEGA, sec_r, RHO; mu=MU, asound=ASOUND)
        outs = solve.(Ref(rotor), sections, ops)
        T, Q = thrusttorque(rotor, sections, outs)
        eff, CT, CQ = nondim(T, Q, Vc, OMEGA, RHO, rotor, "propeller")
        push!(ct_rows, (ncrit, Vc, J, T, Q, CT, CQ, eff))
        @printf("  Vc=%7.4f m/s  J=%.4f  T=%8.4f N  CT=%.5f  CQ=%.6f\n", Vc, J, T, CT, CQ)

        for i in 1:nsec
            o = outs[i]
            Γ = 0.5 * o.W * sec_chord[i] * o.cl
            push!(radial_rows, (; ncrit, Vc, J, r=sec_r[i], r_over_R=sec_r[i]/R,
                                chord=sec_chord[i], twist_rad=sec_theta[i],
                                Re=sec_Re[i], Mach=sec_Mach[i],
                                alpha_deg=rad2deg(o.alpha), phi_deg=rad2deg(o.phi),
                                cl=o.cl, cd=o.cd, a=o.a, ap=o.ap, u=o.u, v=o.v,
                                W=o.W, Np=o.Np, Tp=o.Tp, Gamma=Γ); promote=true)
        end
    end
end

# ------------------------------------------------------------------ output ----
radial_csv = joinpath(SAVE_PATH, "rotor_hover_ccblade_radial.csv")
ct_csv     = joinpath(SAVE_PATH, "rotor_hover_ccblade_CT_vs_J.csv")
CSV.write(radial_csv, radial_rows)
CSV.write(ct_csv, ct_rows)
println("\nWrote $(radial_csv)")
println("Wrote $(ct_csv)")

# long-format polar data (the converged XFOIL points fed to CCBlade, pre-Viterna)
polar_rows = DataFrame(ncrit=Int[], section=Int[], r_over_R=Float64[], Re=Float64[],
                       Mach=Float64[], alpha_deg=Float64[], cl=Float64[], cd=Float64[])
for ncrit in NCRIT_LIST, i in 1:nsec
    p = polar_data[ncrit][i]
    for k in eachindex(p.alpha_deg)
        push!(polar_rows, (ncrit, i, sec_r[i]/R, sec_Re[i], sec_Mach[i],
                           p.alpha_deg[k], p.cl[k], p.cd[k]))
    end
end
polar_csv = joinpath(SAVE_PATH, "rotor_hover_ccblade_polars.csv")
CSV.write(polar_csv, polar_rows)
println("Wrote $(polar_csv)")

# hover operating point (smallest |Vc|) used for the sectional/spanwise comparison
Vc_hover = VC_LIST[argmin(abs.(VC_LIST))]

# ---- per-ncrit hover sectional CSVs (for the panel-vs-BEM spanwise comparison) ----
# dTdr_total = B * Np is the total (both-blade) thrust per unit radius [N/m]; Np is
# CCBlade's per-blade normal force per unit length.
for ncrit in NCRIT_LIST
    sub = radial_rows[(radial_rows.ncrit .== ncrit) .& (radial_rows.Vc .== Vc_hover), :]
    sect = DataFrame(r_over_R=sub.r_over_R, r_m=sub.r, chord_m=sub.chord,
                     alpha_deg=sub.alpha_deg, phi_deg=sub.phi_deg,
                     W=sub.W, u=sub.u, v=sub.v, Np=sub.Np, Tp=sub.Tp,
                     dTdr_total=B .* sub.Np, Gamma=sub.Gamma)
    fname = joinpath(SAVE_PATH, "rotor_hover_ccblade_sectional_ncrit$(ncrit).csv")
    CSV.write(fname, sect)
    println("Wrote $(fname)")
end

# ---- BEM spanwise loading plot (dT/dr total vs r/R, one line per ncrit) ----
let fig_ax = plt.subplots(figsize=(6, 4))
    fig, ax = fig_ax
    for ncrit in NCRIT_LIST
        sub = radial_rows[(radial_rows.ncrit .== ncrit) .& (radial_rows.Vc .== Vc_hover), :]
        ax.plot(sub.r_over_R, B .* sub.Np, "-o"; markersize=3, label="ncrit=$(ncrit)")
    end
    ax.set_xlabel("r/R"); ax.set_ylabel("dT/dr (both blades) [N/m]")
    ax.set_title(@sprintf("BEM spanwise loading, RPM=%.0f, hover", RPM))
    ax.grid(true); ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(joinpath(SAVE_PATH, "rotor_hover_ccblade_spanwise_loading.png"), dpi=150)
    plt.close()
end

# ---- plots ----
# Radial plots are drawn at hover (smallest Vc), one line per ncrit, to isolate
# the transition-parameter effect without an 8-curve Vc x ncrit tangle.
function plot_radial(col, ylabel, fname)
    fig, ax = plt.subplots(figsize=(6, 4))
    for ncrit in NCRIT_LIST
        sub = radial_rows[(radial_rows.ncrit .== ncrit) .& (radial_rows.Vc .== Vc_hover), :]
        ax.plot(sub.r_over_R, sub[!, col], "-o"; markersize=3,
                label="ncrit=$(ncrit)")
    end
    ax.set_xlabel("r/R"); ax.set_ylabel(ylabel)
    ax.set_title(@sprintf("hover (Vc=%.4f m/s)", Vc_hover))
    ax.grid(true); ax.legend(fontsize=7)
    fig.tight_layout(); fig.savefig(joinpath(SAVE_PATH, fname), dpi=150)
    plt.close()
end

plot_radial(:Np,       "Normal loading Np [N/m]",     "radial_loading.png")
plot_radial(:phi_deg,  "Inflow angle phi [deg]",      "radial_inflow_angle.png")
plot_radial(:u,        "Axial induced velocity u [m/s]", "radial_induced_velocity.png")
plot_radial(:Gamma,    "Circulation Gamma [m^2/s]",   "radial_circulation.png")

# ---- lift-polar plots (cl vs alpha; converged XFOIL data, pre-Viterna) ----
# (1) one figure per ncrit: all sections, colored by r/R.
cmap = plt.matplotlib.cm.viridis
for ncrit in NCRIT_LIST
    fig, ax = plt.subplots(figsize=(6, 4.5))
    for i in 1:nsec
        p = polar_data[ncrit][i]
        ax.plot(p.alpha_deg, p.cl, "-"; color=cmap((sec_r[i]/R - sec_r[1]/R) /
                (sec_r[end]/R - sec_r[1]/R)), linewidth=1.0)
    end
    sm = plt.matplotlib.cm.ScalarMappable(; cmap=cmap,
            norm=plt.matplotlib.colors.Normalize(vmin=sec_r[1]/R, vmax=sec_r[end]/R))
    fig.colorbar(sm; ax=ax, label="r/R")
    ax.set_xlabel("alpha [deg]"); ax.set_ylabel("cl")
    ax.set_title("Lift polars used (XFOIL, ncrit=$(ncrit))")
    ax.grid(true)
    fig.tight_layout(); fig.savefig(joinpath(SAVE_PATH, "polars_cl_ncrit$(ncrit).png"), dpi=150)
    plt.close()
end

# (2) representative sections (nearest r/R = 0.25, 0.5, 0.75, 0.95): cl vs alpha,
# one line per ncrit, to show the transition-parameter sensitivity directly.
rep_targets = [0.25, 0.50, 0.75, 0.95]
rep_idx = [argmin(abs.(sec_r ./ R .- t)) for t in rep_targets]
fig, axs = plt.subplots(2, 2; figsize=(9, 7))
for (sp, i) in enumerate(rep_idx)
    ax = axs[(sp - 1) ÷ 2, (sp - 1) % 2]   # row-major indexing into the 2x2 array
    for ncrit in NCRIT_LIST
        p = polar_data[ncrit][i]
        ax.plot(p.alpha_deg, p.cl, "-o"; markersize=2, label="ncrit=$(ncrit)")
    end
    ax.set_title(@sprintf("r/R=%.2f  Re=%.0f", sec_r[i]/R, sec_Re[i]))
    ax.set_xlabel("alpha [deg]"); ax.set_ylabel("cl"); ax.grid(true); ax.legend(fontsize=7)
end
fig.tight_layout(); fig.savefig(joinpath(SAVE_PATH, "polars_cl_vs_ncrit.png"), dpi=150)
plt.close()

# CT vs J, one line per ncrit
fig, ax = plt.subplots(figsize=(6, 4))
for ncrit in NCRIT_LIST
    sub = ct_rows[ct_rows.ncrit .== ncrit, :]
    ax.plot(sub.J, sub.CT, "-o"; label="CCBlade BEM (ncrit=$(ncrit))")
end
ax.axhline(CT_PANEL; color="k", linestyle="--", label=@sprintf("panel %.4f", CT_PANEL))
ax.axhline(CT_EXPERIMENT; color="gray", linestyle=":", label=@sprintf("experiment %.3f", CT_EXPERIMENT))
ax.set_xlabel("advance ratio J = Vc/(nD)"); ax.set_ylabel("CT = T/(rho n^2 D^4)")
ax.grid(true); ax.legend(fontsize=8)
fig.tight_layout(); fig.savefig(joinpath(SAVE_PATH, "CT_vs_J.png"), dpi=150)
plt.close()

# ---- summary ----
println("\n" * "="^60)
println("Hover (Vc=$(Vc_hover) m/s) CCBlade CT by ncrit:")
for ncrit in NCRIT_LIST
    sub = ct_rows[(ct_rows.ncrit .== ncrit) .& (ct_rows.Vc .== Vc_hover), :]
    ct = sub.CT[1]
    @printf("  ncrit=%2d:  CT = %.5f   (BEM/panel = %.3f, BEM/exp = %.3f)\n",
            ncrit, ct, ct/CT_PANEL, ct/CT_EXPERIMENT)
end
@printf("  reference:  panel CT = %.5f,  experiment CT = %.5f\n", CT_PANEL, CT_EXPERIMENT)
println("="^60)
