name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.8', '1.10', '1.11']
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Install matplotlib
        run: if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get update; sudo apt-get install -y python3-matplotlib --fix-missing; fi
        shell: bash
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Override Conda Python
        run: if [ "$RUNNER_OS" = "Linux" ]; then julia -e 'import Pkg; Pkg.add("PyCall"); ENV["PYTHON"]="/usr/bin/python3"; Pkg.build("PyCall")'; fi
        shell: bash
      - name: Install dependencies
        env:
          PYTHON: ""
        run: julia -e 'using Pkg; Pkg.add(url="https://github.com/byuflowlab/FastMultipole", rev="d21d242d081ea8c9c19655097d83413b1f783d2d")'
      # - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
